### ISSUE TITLE
won't install

### ISSUE THREAD

**Issue by theskillwithin** [JounQin/react-qrious#2]
```➜  dashgiveaway git:(master) ✗ yarn add react-qrious
yarn add v1.5.1
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > react-qrious@1.0.4" has unmet peer dependency "prop-types@^15.6.0".
[5/5] 📃  Building fresh packages...
[-/3] ⠄ waiting...
[2/3] ⠄ fsevents: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v59-darwin-x64.tar.gz
[3/3] ⠄ canvas: spawn args   '-Goutput_dir=.' ]
[-/3] ⠄ waiting...
error An unexpected error occurred: "/Users/Austin/Projects/dashgiveaway/node_modules/canvas: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /Users/Austin/Projects/dashgiveaway/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@9.8.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/Austin/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Austin/Projects/dashgiveaway/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Austin/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Austin/.node-gyp/9.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Austin/.node-gyp/9.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/Austin/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/Austin/.node-gyp/9.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/Austin/Projects/dashgiveaway/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/Austin/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command \"/Users/Austin/.nvm/versions/node/v9.8.0/bin/node\" \"/Users/Austin/.nvm/versions/node/v9.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/Austin/Projects/dashgiveaway/node_modules/canvas
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.6.2
```

**Comment by JounQin** [comment]
Please install `qrious` or `node-qrious` first then try `react-qrious@1.0.5` again.

Sorry for delay.
